### ISSUE TITLE
Xwayland not rendering with Mir-Kiosk 0.31

### ISSUE THREAD

**Issue by gerboland** [MirServer/mir-kiosk#5] opened 2018-04-16 11:47 UTC
Please try this:
Install Ubuntu Core into a VM
Install the latest mir-kiosk snap (snap install --beta mir-kiosk)
Grab, build and install this snap:
https://code.launchpad.net/~gerboland/+git/xeyes-snap/+ref/master
with --devmode. Connect the wayland-socket-dir interface:
snap connect xeyes:wayland-socket-dir mir-kiosk:wayland-socket-dir

Run it with "sudo snap run xeyes.xeyes-mir". You should see a white screen with the xeyes. But I see nothing.

Some simple debugging: Can run exclusively Xwayland with this:

sudo snap run --shell xeyes.xeyes-mir

WAYLAND_DEBUG=1 LIBGL_DRIVERS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/dri LD_LIBRARY_PATH=$SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl XDG_RUNTIME_DIR=$SNAP_DATA/wayland LD_PRELOAD=$SNAP/lib/libxwayland-preload.so $SNAP/usr/bin/Xwayland -wr :0

Notice the "wl_surface@3.attach(nil, 0, 0)" in particular - no buffer is being attached?!

**Comment by gerboland** [comment] 2018-04-16 15:56
Hmm, think similar can be reproduced as follows. I'm working in a VM, in case it is relevant:
- install Ubuntu Xenial (normal desktop)
- add Mir release ppa and ensure Xenial updates is enabled
- install miral-shell, Xwayland and xeyes

In one terminal, run:
sudo XDG_RUNTIME_DIR=/tmp miral-shell --vt 4 --arw-file
and you should VT switch to the mir shell.

In another terminal (I SSHed in):
sudo WAYLAND_DEBUG=1 XDG_RUNTIME_DIR=/tmp Xwayland -wr :1
(a white window *should* appear now, but I don't get that)

And then, try running:
sudo DISPLAY=:1 xeyes 

I don't see anything X related being rendered. The WAYLAND_DEBUG output does suggest a proper buffer is being attached to the wl_surfaces though...

**Comment by gerboland** [comment] 2018-04-16 15:59
If I follow those instructions but on Mir-on-X (i.e. remove the "--vt 4" flag) all works ok

**Comment by AlanGriffiths** [comment] 2018-04-17 10:29
For reference (on xenial):

Running miral-shell through:
    $ miral-desktop -qt-mirclient

And xeyes through:
    $ miral-xrun -Xwayland xeyes

works for me.

**Comment by AlanGriffiths** [comment] 2018-04-17 11:21
@gerboland I can confirm that following your instructions I don't see xeyes.

But I do see sensible debug output, including pointer events being passed touching the trackpad, Xwayland is doing *something*.

**Comment by AlanGriffiths** [comment] 2018-04-17 11:43
Running the client from the VT instead of an SSH session works:

If instead "$ sudo DISPLAY=:1 xeyes" I first run a terminal:

    $ XDG_RUNTIME_DIR=/tmp QT_QPA_PLATFORM=ubuntumirclient qterminal

And run "$ sudo DISPLAY=:1 xeyes" from this terminal it works.

**Comment by AlanGriffiths** [comment] 2018-04-17 13:21
@gerboland I put mir-team/dev back on my xenial system and tried it. I found that it failed as you wrote it. But then I discovered that if I also have another client running then it works.

ssh(1)
$ sudo XDG_RUNTIME_DIR=/tmp miral-shell --vt 4 --arw-file

ssh(2)
$ mir_demo_client_multiwin -m /tmp/mir_socket& sudo WAYLAND_DEBUG=1 XDG_RUNTIME_DIR=/tmp Xwayland -wr :1

ssh(3)
$ sudo DISPLAY=:1 xeyes

That suggests there's a problem getting the compositor to use the first buffer which should result in a frame notification back to the Xwayland client.

**Comment by gerboland** [comment] 2018-04-17 13:23
That would concur with one failure case I was seeing, where Xwayland would submit a buffer and buffer-done callback, and its callback was never fired so it just sat there.

**Comment by AlanGriffiths** [comment] 2018-04-17 13:36
1. This is exactly the problem I saw when trying to write a wlcs test case. I assumed there was something wrong with my test! (https://github.com/MirServer/wlcs/tree/frame-submission)

2. I wonder if 0.30 only "worked" because it has the longer running EGL based intro? Maybe waiting until that finishes before starting Xwayland would also be broken.

**Comment by gerboland** [comment] 2018-04-17 13:39
I do suspect there's a race involved, as once in a blue moon it has just worked

**Comment by AlanGriffiths** [comment] 2018-04-17 13:56
This seems to be a Mir problem: https://github.com/MirServer/mir/issues/328

**Comment by AlanGriffiths** [comment] 2018-04-18 14:29
Fixed upstream: https://github.com/MirServer/mir/pull/329

**Comment by AlanGriffiths** [comment] 2018-05-10 13:21
Fixed in Mir release 0.31.2 which has been released as a snap.

**Closed as completed by AlanGriffiths** 2018-05-10 13:21 UTC
